env:
  node: true
  jest: true
  browser: true
  es2021: true

extends:
  - "airbnb-base"
  - "plugin:jest/recommended"

parser: "@babel/eslint-parser"

plugins:
  - jest
  - babel

rules:
  no-console: 0
  import/extensions: 0
